//
// Generated file, do not edit! Created by opp_msgtool 6.2 from msg/MyKDS.msg.
//

#ifndef __MYKDS_M_H
#define __MYKDS_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0602
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class HelloMsg;
class DominateMsg;
/**
 * Class generated from <tt>msg/MyKDS.msg:5</tt> by opp_msgtool.
 * <pre>
 * // HelloMsg paket tanımı
 * packet HelloMsg
 * {
 *     int originId;
 *     int ttl;
 *     int seq;
 * }
 * </pre>
 */
class HelloMsg : public ::omnetpp::cPacket
{
  protected:
    int originId = 0;
    int ttl = 0;
    int seq = 0;

  private:
    void copy(const HelloMsg& other);

  protected:
    bool operator==(const HelloMsg&) = delete;

  public:
    HelloMsg(const char *name=nullptr, short kind=0);
    HelloMsg(const HelloMsg& other);
    virtual ~HelloMsg();
    HelloMsg& operator=(const HelloMsg& other);
    virtual HelloMsg *dup() const override {return new HelloMsg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getOriginId() const;
    virtual void setOriginId(int originId);

    virtual int getTtl() const;
    virtual void setTtl(int ttl);

    virtual int getSeq() const;
    virtual void setSeq(int seq);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const HelloMsg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, HelloMsg& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>msg/MyKDS.msg:13</tt> by opp_msgtool.
 * <pre>
 * // DominateMsg paket tanımı
 * packet DominateMsg
 * {
 *     int dominatorId;
 * }
 * </pre>
 */
class DominateMsg : public ::omnetpp::cPacket
{
  protected:
    int dominatorId = 0;

  private:
    void copy(const DominateMsg& other);

  protected:
    bool operator==(const DominateMsg&) = delete;

  public:
    DominateMsg(const char *name=nullptr, short kind=0);
    DominateMsg(const DominateMsg& other);
    virtual ~DominateMsg();
    DominateMsg& operator=(const DominateMsg& other);
    virtual DominateMsg *dup() const override {return new DominateMsg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getDominatorId() const;
    virtual void setDominatorId(int dominatorId);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const DominateMsg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, DominateMsg& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline HelloMsg *fromAnyPtr(any_ptr ptr) { return check_and_cast<HelloMsg*>(ptr.get<cObject>()); }
template<> inline DominateMsg *fromAnyPtr(any_ptr ptr) { return check_and_cast<DominateMsg*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __MYKDS_M_H

