[General]
network = my_kds_project.KDSNetwork
sim-time-limit = 50s
mykds.KDSNetwork.numNodes = 20
mykds.KDSNetwork.areaX = 800
mykds.KDSNetwork.areaY = 600
mykds.KDSNetwork.txRange = 200
mykds.KDSNetwork.k = 2

# Node parameters
*.txRange = 200
*.k = 2
*.helloInterval = 1.0

